receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4333

exporters:
  neo4jtraces:
    datasource: bolt://localhost:7687/?username=neo4j&password=neo4jneo4j&db=neo4j
  logging:
    #    verbosity: detailed
    sampling_initial: 1
processors:
  batch:
    send_batch_size: 10000
    send_batch_max_size: 11000
    timeout: 10s
  signozspanmetrics/prometheus:
    metrics_exporter: prometheus
    latency_histogram_buckets: [100us, 1ms, 2ms, 6ms, 10ms, 50ms, 100ms, 250ms, 500ms, 1000ms, 1400ms, 2000ms, 5s, 10s, 20s, 40s, 60s ]
    dimensions_cache_size: 100000
    dimensions:
      - name: service.namespace
        default: default
      - name: deployment.environment
        default: default
      # This is added to ensure the uniqueness of the timeseries
      # Otherwise, identical timeseries produced by multiple replicas of
      # collectors result in incorrect APM metrics
      - name: 'signoz.collector.id'
  resourcedetection:
    # Using OTEL_RESOURCE_ATTRIBUTES envvar, env detector adds custom labels.
    detectors: [env, system] # include ec2 for AWS, gce for GCP and azure for Azure.
    timeout: 2s

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [neo4jtraces, logging]
